# This is a basic workflow that is manually triggered

name: Get latest ISOs links

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

permissions:
  contents: write

jobs:
  get:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Get latest ISOs links
      run: curl -s https://distrowatch.com | grep 'News".*\.iso' | cut -d '"' -f4,6 | sed 's/"/ /g' | column --table | tee -a ISOs.list

    - name: "Git Config"
      run: |
        git config --global user.name "${{ github.repository_owner }}"
        git config --global user.email "noreply@github.com"

    - name: Update list
      run: |
        git add ISOs.list
        git commit -m "update ISOs list"
        git push
