--- # This is a basic workflow to help you get started with Actions

name: List all supported ISOs

on:
  push:
    paths:
      - 'quickget'
    branches: ['**'] #'!master' # excludes master
  pull_request:
    branches: ['**'] # matches every branch

  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  list-ISOs:
    runs-on: self-hosted

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Prerequisites
        run: |
          echo "               ISOs:"
          ./quickget -li
