--- # This is a basic workflow to help test quickget

name: quickget test

# Controls when the action will run.
on:
  # Build at 00:00 on every 12th day-of-month.
  #schedule:
  #  - cron: "0 0 */12 * *"
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: '**' #'!master' # excludes master
    paths: [ quickget ]
  pull_request:
    branches: '**' # matches every branch
    paths:
      - quickget

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:


  Supported:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: List supported
        run: |
          echo -e "\n\n               Supported:\n"
          ./quickget -ls | tee supported.txt
          echo -e "\n\n               Finished\n\n"

      - uses: actions/upload-artifact@v4
        with:
          name: supported
          path: supported.txt


  OSinfo:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: List supported
        run: |
          echo -e "\n\n               Supported:\n"
          distros="$(./quickget | sed '/^$/q' | tail -n +3)"
          for os in ${distros}; do
            ./quickget -i "${os}" | tee osinfo.txt
          done
          echo -e "\n\n               Finished\n\n"

      - uses: actions/upload-artifact@v4
        with:
          name: osinfo
          path: osinfo.txt

  ISOs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: List ISOs
        run: |
          echo -e "\n\n               ISOs:\n\n"
          ./quickget -li | tee isos.txt
          echo -e "\n\n               Finished\n\n"

      - uses: actions/upload-artifact@v4
        with:
          name: isos
          path: isos.txt


  Test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: ISOs availability
        run: |
          echo -e "\n\n               ISOs availability:\n\n"
          ./quickget -ti | tee isostest.txt
          echo -e "\n\n               Finished\n\n"

      - uses: actions/upload-artifact@v4
        with:
          name: isostest
          path: isostest.txt
