--- # reviewdog
name: 'Run shellcheck with reviewdog'

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  shellcheck:
    permissions:
      checks: write
      contents: read
      pull-requests: write
    name: 'Run shellcheck with reviewdog'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haya14busa/action-cond@v1
        id: reporter
        with:
          cond: ${{ github.event_name == 'pull_request' }}
      - uses: reviewdog/action-shellcheck@v1
        with:
          reporter: ${{ steps.reporter.outputs.value }}
          level: error
          github_token: ${{ secrets.github_token }}
          pattern: |
            quickget
            quickemu
