name: reviewdog

on: [push, pull_request, workflow_dispatch]

#jobs:

  #checks:
    #name: Check scripts
    #runs-on: ubuntu-latest

    #strategy:
      #matrix:
        #package:
        # - "**/*.sh" # checks all .sh files
        #- quickget
        #- quickemu
    #steps:
      #- uses: actions/checkout@v3
      #- uses: cachix/install-nix-action@v17
        #with:
          #install_url: https://nixos.org/nix/install
          #extra_nix_config: |
            #auto-optimise-store = true
            #experimental-features = nix-command flakes
      #- run: nix run nixpkgs#shellcheck -- -S error ${{ matrix.package }}

jobs:
  quickemu-check:
    name: runner / quickemu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Change reporter.
          path: "." # Optional.
          pattern: "quickemu" # Optional.
          exclude: "./.git/*" # Optional.
          check_all_files_with_shebangs: "false" # Optional.
  quickget-check:
    name: runner / quickget
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Change reporter.
          path: "." # Optional.
          pattern: "quickget" # Optional.
          exclude: "./.git/*" # Optional.
          check_all_files_with_shebangs: "false" # Optional.
