name: "update changed OS"

on:
  #schedule:
    #- cron: '0/180 * * * *'
  push:
    branches:
      - master-patched
    paths:
      - actions/**
  pull_request:
    branches:
      - master-patched
    paths:
      - actions/**
  workflow_dispatch:
    inputs:
      what_test:
        description: "test OS: (space between)"
        required: false
        default: ""
        type: string

jobs:
  fill:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: fill
        run: |
          #git status
          chmod a+x action
          echo "Input check"
          if [ ! -z "${{ github.event.inputs.what_test }}" ]; then
            echo "Input was used"
            changed="${{ github.event.inputs.what_test }}"
          else
            echo "Finding git change"
            changed=$(git diff --name-only HEAD^ HEAD | grep '^actions/')
          fi
          echo "Changed check"
          if [ -z "${changed}" ]; then
            echo "Nothing choosed or changed"
            exit 0
          fi
          echo "Check run"
          for os in ${changed}; do
            ./action ${os}
          done
          echo "Sorting all"
          sort -u < TODO/all | tee TODO/all

      - name: push
        run: |
          git config --global user.name "${{ github.repository_owner }}"
          git config --global user.email "noreply@github.com"
          #git status
          #git add . || echo "add . failed"
          git add TODO/all || echo "add TODO/all failed"
          git add actions || echo "add actions failed"
          rm -f public/tmp* || echo "Removing public/tmp* failed"
          git add public || echo "add public failed"
          git add --all || echo "add --all failed"
          git commit -m "update supported" || echo "commit failed"
          git push || echo "push failed"
          git status
